spring.application.name=AutomobileInsuranceSystem

#DB Settings
spring.datasource.url=jdbc:mysql://localhost:3306/automobile_insurance_sys?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Heman@5810

#Hibernate Settings
# tells Hibernate to automatically update the database
spring.jpa.hibernate.ddl-auto=update